__future__          atexit              html                sched
__main__            audioop             http                scrolledlist
_abc                autocomplete        hyperparser         search
_ast                autocomplete_w      idle                searchbase
_asyncio            autoexpand          idle_test           searchengine
_bisect             base64              idlelib             secrets
_blake2             bdb                 imaplib             select
_bootlocale         binascii            imghdr              selectors
_bz2                binhex              imp                 setuptools
_codecs             bisect              importlib           shelve
_codecs_cn          browser             inspect             shlex
_codecs_hk          builtins            io                  shutil
_codecs_iso2022     bz2                 iomenu              signal
_codecs_jp          cProfile            ipaddress           site
_codecs_kr          calendar            itertools           smtpd
_codecs_tw          calltip             json                smtplib
_collections        calltip_w           keyword             sndhdr
_collections_abc    cgi                 lib2to3             socket
_compat_pickle      cgitb               linecache           socketserver
_compression        chunk               locale              sqlite3
_contextvars        cmath               logging             squeezer
_csv                cmd                 lzma                sre_compile
_ctypes             code                macosx              sre_constants
_ctypes_test        codecontext         macpath             sre_parse
_datetime           codecs              mailbox             ssl
_decimal            codeop              mailcap             stackviewer
_dummy_thread       collections         mainmenu            stat
_elementtree        colorizer           marshal             statistics
_functools          colorsys            math                statusbar
_hashlib            compileall          mimetypes           string
_heapq              concurrent          mmap                stringprep
_imp                config              modulefinder        struct
_io                 config_key          msilib              subprocess
_json               configdialog        msvcrt              sunau
_locale             configparser        multicall           symbol
_lsprof             contextlib          multiprocessing     symtable
_lzma               contextvars         netrc               sys
_markupbase         copy                nntplib             sysconfig
_md5                copyreg             nt                  tabnanny
_msi                crypt               ntpath              tarfile
_multibytecodec     csv                 nturl2path          telnetlib
_multiprocessing    ctypes              numbers             tempfile
_opcode             curses              opcode              test
_operator           dataclasses         operator            textview
_osx_support        datetime            optparse            textwrap
_overlapped         dbm                 os                  this
_pickle             debugger            outwin              threading
_py_abc             debugger_r          paragraph           time
_pydecimal          debugobj            parenmatch          timeit
_pyio               debugobj_r          parser              tkinter
_queue              decimal             pathbrowser         token
_random             delegator           pathlib             tokenize
_sha1               difflib             pdb                 tooltip
_sha256             dis                 percolator          trace
_sha3               distutils           pickle              traceback
_sha512             doctest             pickletools         tracemalloc
_signal             dummy_threading     pip                 tree
_sitebuiltins       dynoption           pipes               tty
_socket             easy_install        pkg_resources       turtle
_sqlite3            editor              pkgutil             turtledemo
_sre                email               platform            types
_ssl                encodings           plistlib            typing
_stat               ensurepip           poplib              undo
_string             enum                posixpath           unicodedata
_strptime           errno               pprint              unittest
_struct             exam                profile             urllib
_symtable           faulthandler        pstats              uu
_testbuffer         filecmp             pty                 uuid
_testcapi           fileinput           py_compile          venv
_testconsole        filelist            pyclbr              warnings
_testimportmultiple fnmatch             pydoc               wave
_testmultiphase     formatter           pydoc_data          weakref
_thread             fractions           pyexpat             webbrowser
_threading_local    ftplib              pyparse             window
_tkinter            functools           pyshell             winreg
_tracemalloc        gc                  query               winsound
_warnings           genericpath         queue               wsgiref
_weakref            getopt              quopri              xdrlib
_weakrefset         getpass             random              xml
_winapi             gettext             re                  xmlrpc
abc                 glob                redirector          xxsubtype
aifc                grep                replace             zipapp
antigravity         gzip                reprlib             zipfile
argparse            hashlib             rlcompleter         zipimport
array               heapq               rpc                 zlib
ast                 help                rstrip              zoomheight
asynchat            help_about          run                 zzdummy
asyncio             history             runpy               
asyncore            hmac                runscript           
